name: Deploy Frozen Flask to GitHub Pages

on:
  push:
    branches:
      - main  # Run this workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Set up Python
    - name: Set up Python 3.6
      uses: actions/setup-python@v4
      with:
        python-version: 3.6

    # Step 2: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r dependencies.txt

    # Step 4: Freeze the Flask app
    - name: Freeze the Flask app
      env:
        FLASK_APP: app.py
      run: |
        flask freeze

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # Use the output directory from `flask freeze`
